/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank;

import java.util.ArrayList;



public class App {
    public static void main(String[] args) {
        // Create a list of customers from file
        ArrayList<Customer> customersList = CustomerFromFile.getCustomersList();


        // Iterate through customers list printing out customer info and monthly payment
        for (Customer customer : customersList) {
            customer.presentCustomer();
        }
    }
}
